name: MOBI-DICK-test

channels:
  - conda-forge
  - bioconda
  - yuxiang

dependencies:
  - python=3.9.9
  - h5py=3.1
  - megahit=1.2.9
  - repeatmasker=4.1.2
  - bowtie2=2.4.4
  - trim-galore=0.6.10
  - samtools=1.12
  - bam2fastq=1.1.0
  - pigz=2.6
  - prinseq=0.20.4
  - pandas=2.1.1
  - bs4=4.12.2
  - krona=2.8.1
